# Generated by Django 2.2.13 on 2023-05-06 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20230506_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('House', 'House'), ('Gold', 'Gold'), ('Electronics', 'Electronics'), ('musical instruments', 'musical instruments'), ('smart phones', 'smart phones')], max_length=100),
        ),
    ]
